<a href="https://colab.research.google.com/github/yeesem/Deep_Learning/blob/main/Preparing_Time_Series_Features_and_Labels_in_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
# Generate a tf dataset with 10 elements
dataset = tf.data.Dataset.range(10)

# Preview the result
for val in dataset:
  print(val)

for val in dataset:
  print(val.numpy())

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
0
1
2
3
4
5
6
7
8
9


In [5]:
# Generate a tf dataset with 10 elements
dataset = tf.data.Dataset.range(10)

# Window the data
dataset = dataset.window(size = 5,shift = 1)

# Print the result
for window_dataset in dataset:
  print(window_dataset)

for window_dataset in dataset:
  print([item.numpy() for item in window_dataset])

<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]


In [7]:
# Generate a tf dataset with 10 elements
dataset = tf.data.Dataset.range(10)

# Window the data in specified size
dataset = dataset.window(size = 5,shift = 1,drop_remainder = True)

# Print the result
for val in dataset:
  print([item.numpy() for item in val])

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]


In [8]:
# Generate a tf dataset with 10 elements (i.e. numbers 0 to 9)
dataset = tf.data.Dataset.range(10)

# Window the dataset
dataset = dataset.window(5,shift = 1,drop_remainder = True)

# Flatten the winowo by putting its element in a single batch
dataset = dataset.flat_map(lambda window : window.batch(5))

# Print the result
for window in dataset:
  print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [10]:
# Generate a tf dataset with 10 elements (i.e. numbers 0 to 9)
dataset = tf.data.Dataset.range(10)

# Window the data but only take those with the specified size
dataset = dataset.window(5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch
dataset = dataset.flat_map(lambda window: window.batch(5))

# Create tuples with features and labels
dataset = dataset.map(lambda window : (window[:-1],window[-1]))

for x,y in dataset:
  print("X = ",x.numpy())
  print("y = ",y.numpy())
  print()

X =  [0 1 2 3]
y =  4

X =  [1 2 3 4]
y =  5

X =  [2 3 4 5]
y =  6

X =  [3 4 5 6]
y =  7

X =  [4 5 6 7]
y =  8

X =  [5 6 7 8]
y =  9



In [11]:
# Generate a tf dataset with 10 elements (i.e. numbers 0 to 9)
dataset = tf.data.Dataset.range(10)

# Window the data but only take those with the specified size
dataset = dataset.window(5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch
dataset = dataset.flat_map(lambda window: window.batch(5))

# Create tuples with features (first four elements of the window) and labels (last element)
dataset = dataset.map(lambda window: (window[:-1], window[-1]))

# Shuffle the windows
dataset = dataset.shuffle(buffer_size = 10)

# Create batches of windows
dataset = dataset.batch(2).prefetch(1)

# Print the result
for x,y in dataset:
  print("X : ",x.numpy())
  print("y : ",y.numpy())
  print()

X :  [[0 1 2 3]
 [3 4 5 6]]
y :  [4 7]

X :  [[1 2 3 4]
 [4 5 6 7]]
y :  [5 8]

X :  [[5 6 7 8]
 [2 3 4 5]]
y :  [9 6]

